### ISSUE TITLE
Plugin add fails if android platform exists if it can not find shelljs

### ISSUE THREAD

**Issue by stefangordon** [AllJoyn-Cordova/cordova-plugin-alljoyn#1]
Haven't investigated this at all, we'll need to figure out what the dependency is and the right way to deal with it (instructions, removal, inclusion, etc).

``` sh
Cloning ajtcl-android from: https://github.com/irjudson/ajtcl-android.git
Failed to install 'org.allseen.alljoyn':Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\Keir\Documents\cordova-chat-alljoyn\plugins\org.allseen.alljoyn\scripts\androidAfter
PluginInstall.js:6:10)
```

**Comment by ResmiMR** [comment]
Hello,
Iam also facing the same issue.Alljoyn sample chat app is even not working.What will be the isse?Any help will be highly appreciated.Urgent!!

**Comment by vjrantal** [comment]
First of all, thanks for your interest towards the project!

You can get the shelljs dependency fixed by running following command in your Cordova project root:

```
$ npm install shelljs
```

However, if you are trying to get the chat sample running on Android, you will unfortunately run into other issues as well, because the Android support hasn't yet been finalized.

This particular issue will soon go away once we integrate a better Android build flow that we are working with at https://github.com/phongcao/cordova-plugin-alljoyn .

**Comment by ResmiMR** [comment]
Thank you so much for your reply.When i was trying to run the chat app in android,the channels are even not detecting on the devices.Alljoyn was installed without showing any errors.But while running ,it couldnt get the Window.Alljoyn in the service.Please help.

**Comment by vjrantal** [comment]
What you see sounds as expected since the Android platform implementation isn't yet completed.

If you want to test a functional chat app today, you have to build for iOS or Windows / Windows Phone. There is work ongoing for the Android support, but it isn't there yet.

**Comment by vjrantal** [comment]
The new way of building for Android has landed to our master branch and this issue is not relevant anymore, because shelljs isn't used.
