### ISSUE TITLE
Windows build requires manual steps

### ISSUE THREAD

**Issue by stefangordon** [AllJoyn-Cordova/cordova-plugin-alljoyn#14]
It appears these manual steps are required for making Windows builds.  We should figure out what specific issues block a pure command line build/run and come up with a plan for them.  We should also document the required SDK/VS versions so we can update the readme for samples.
- use the private checkout of cordova-cli/lib that were referenced
- When the app is generated i open the solution in vs2013
- Flip the build config to x86, set default startup project to the windows 8.1 app
- Add the capability for internet client & server
- Update the debugging setting to debug both native and script

**Comment by vjrantal** [comment]
Found a way to deal with the capability step, but defining the architecture explicitly seems to be mandatory or at least I didn't figure out how it could be avoided with the current Cordova scripts.

I'd propose closing this issue since the architecture setting is described in the readme at https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn/#using-the-plugin-for-windows-platforms .

**Comment by vjrantal** [comment]
Since no objections to the previous comment, closing this issue.
